OBJ_CATEGORIES = ['person',
'sky',
'building',
'truck',
'bus',
'table',
'shirt',
'chair',
'car',
'train',
'glasses',
'tree',
'boat',
'hat',
'trees',
'grass',
'pants',
'road',
'motorcycle',
'jacket',
'monitor',
'wheel',
'umbrella',
'plate',
'bike',
'clock',
'bag',
'shoe',
'laptop',
'desk',
'cabinet',
'counter',
'bench',
'shoes',
'tower',
'bottle',
'helmet',
'stove',
'lamp',
'coat',
'bed',
'dog',
'mountain',
'horse',
'plane',
'roof',
'skateboard',
'traffic light',
'bush',
'phone',
'airplane',
'sofa',
'cup',
'sink',
'shelf',
'box',
'van',
'hand',
'shorts',
'post',
'jeans',
'cat',
'sunglasses',
'bowl',
'computer',
'pillow',
'pizza',
'basket',
'elephant',
'kite',
'sand',
'keyboard',
'plant',
'can',
'vase',
'refrigerator',
'cart',
'skis',
'pot',
'surfboard',
'paper',
'mouse',
'trash can',
'cone',
'camera',
'ball',
'bear',
'giraffe',
'tie',
'luggage',
'faucet',
'hydrant',
'snowboard',
'oven',
'engine',
'watch',
'face',
'street',
'ramp',
'suitcase']

REL_CATEGORIES = ['on',
'wear',
'has',
'next to',
'sleep next to',
'sit next to',
'stand next to',
'park next',
'walk next to',
'above',
'behind',
'stand behind',
'sit behind',
'park behind',
'in the front of',
'under',
'stand under',
'sit under',
'near',
'walk to',
'walk',
'walk past',
'in',
'below',
'beside',
'walk beside',
'over',
'hold',
'by',
'beneath',
'with',
'on the top of',
'on the left of',
'on the right of',
'sit on',
'ride',
'carry',
'look',
'stand on',
'use',
'at',
'attach to',
'cover',
'touch',
'watch',
'against',
'inside',
'adjacent to',
'across',
'contain',
'drive',
'drive on',
'taller than',
'eat',
'park on',
'lying on',
'pull',
'talk',
'lean on',
'fly',
'face',
'play with',
'sleep on',
'outside of',
'rest on',
'follow',
'hit',
'feed',
'kick',
'skate on']

REL_CATEGORIES_FIT = ['at',
'by',
'wear',
'sit on',
'has',
'in the front of',
'over',
'on',
'beside',
'with',
'above',
'hold',
'on the top of',
'under',
'behind',
'sleep on',
'beneath',
'cover',
'next to',
'near',
'in',
'below']

OBJ_CATEGORIES_FIT = ['shoes',
'dog',
'boat',
'face',
'sky',
'plate',
'post',
'shirt',
'pants',
'street',
'chair',
'train',
'person',
'glasses',
'clock',
'table',
'bottle',
'hat',
'vase',
'watch',
'mountain',
'wheel',
'sofa',
'box',
'monitor',
'umbrella',
'road',
'cup',
'basket',
'airplane',
'bench',
'trees',
'hydrant',
'tree',
'tower',
'bus',
'bag',
'grass',
'laptop',
'building',
'elephant',
'car',
'jacket',
'lamp']

REL_CATEGORIES_FIT_VAL = ['behind', 'touch', 'cover', 'wear', 'ride', 'on the top of', 'next to', 'with', 'beneath', 'by', 'sit on', 'in', 'over', 'beside', 'near', 'sleep on', 'below', 'on the left of', 'in the front of', 'has', 'under', 'hold', 'at', 'on', 'on the right of', 'above']

OBJ_CATEGORIES_FIT_VAL = ['bus', 'sky', 'trees', 'jacket', 'dog', 'box', 'road', 'skateboard', 'desk', 'boat', 'post', 'tower', 'wheel', 'shoes', 'ramp', 'bike', 'basket', 'street', 'glasses', 'table', 'monitor', 'clock', 'jeans', 'bag', 'cup', 'bottle', 'mountain', 'chair', 'sunglasses', 'lamp', 'face', 'umbrella', 'surfboard', 'grass', 'pants', 'tree', 'bench', 'bush', 'pillow', 'laptop', 'airplane', 'helmet', 'building', 'elephant', 'train', 'shoe', 'sofa', 'bed', 'cone', 'motorcycle', 'keyboard', 'person', 'traffic light', 'plate', 'vase', 'shirt', 'phone', 'hat', 'shorts', 'watch', 'hydrant', 'car']
BBOX_KEYPOINTS = [
    'top_left',            # 1
    'top_right',        # 2
    'bottom_right',       # 3
    'bottom_left',        # 4
    'center',       # 5
]

BBOX_HFLIP = {
    'top_left': 'top_right',
    'top_right': 'top_left',
    'bottom_right': 'bottom_left',
    'bottom_left': 'bottom_right',
    'center': 'center',
}
