name: update-stable

on:
  release:
    types:
      - released

jobs:
  update-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Push to stable branch
      run: |
        git pull
        git checkout stable
        git merge master -m "merge master"
        git push
